
[example.LinkedCellList]
pred = "= head |-> ?h &*& (h == null ? absVal == nil : h.nellist(absVal))"

body = "private NonEmptyLinkedCellList head;"

init = "head = null;"

add = """

    if (head == null) {
      head = new NonEmptyLinkedCellList(v);
    } else {
      head.add(v);
    }
"""

getLast = """

    Cell result;
    if (head == null) {
      result = null;
    } else { 
      result = head.getLast(); 
    } 
    return result;
"""

file = """
final class NonEmptyLinkedCellList {
  /*@ predicate nellist(list<Cell> ll) = next |-> ?n
     &*& value |-> ?v
     &*& (n == null ? ll == cons(v, nil)
     : (n.nellist(?r) &*& ll == cons(v, r)));               
    @*/
    
  private Cell value;
  private NonEmptyLinkedCellList next;

  public NonEmptyLinkedCellList(Cell v)
    //@ requires true;
    //@ ensures nellist(cons(v,nil));
  {
    value =v;
    next = null;
  }

  public void add(Cell v)
    //@ requires nellist(?l_old) ;
    //@ ensures nellist(?l) &*& l == (append(l_old, cons(v, nil)));
  {
    if (next == null) {
      NonEmptyLinkedCellList n = new NonEmptyLinkedCellList(v);
      next = n;
    } else {
      next.add(v);
    }
  }

  public Cell getLast()
    //@ requires nellist(?l);
    //@ ensures nellist(l) &*& result == (nth((length(l)) - (1), l));
  {
    Cell result;
    if (next == null) {
      result = value;
    } else {
      //@ open next.nellist(?x);
      result = next.getLast();
    }
    return result;
  }
}
"""

[example.Cell]
body = "private int x;"
pred = "= x |-> absVal"
init = "this.x = 0;"
value = "return this.x;"
set = "this.x = v;"
file = ""
