
package org.contract_lib.contract_chameleon.adapters;

import java.util.Set;

import org.contract_lib.contract_chameleon.Adapter;
import org.contract_lib.contract_chameleon.SharedContextManager;
import org.contract_lib.contract_chameleon.SharedContextManager.InterfaceProvidedContext;
import org.contract_lib.contract_chameleon.contexts.SourcePathsContext;

/** A adapter to check the provided input that is can be translated.
 * <p>
 * The checker might be run in combination with a {@link TranslationAdapter},
 * but can also be run on its own.
 * <p>
 * Data structures that are generated by this adapter can be shared with other adapters,
 * via {@link SharedContextManager}.
 * Note: All adapter must be able to run on their own.
 */
public abstract class CheckerAdapter extends Adapter {

  /**
   * Performs the checks on the provided source files.
   * 
   * @return If the check was successful {@value CheckerAdapterResult#SUCCESS} otherwise {@value CheckerAdapterResult#FAILURE}.
   */
  public abstract CheckerAdapterResult performCheck();

  @Override
  public final void perform() {
    // Execution if the checker is run as a normal adapter.
    switch (this.performCheck()) {
      case SUCCESS -> this.getMessageContext()
          .logInfo(String.format("Checker '%s' successful.", this.getAdapterName()));
      case FAILURE -> this.getMessageContext()
          .logError(String.format("Checker '%s' failed.", this.getAdapterName()));
    }
  }

  @Override
  public Set<Class<? extends InterfaceProvidedContext>> argumentContextsFromInterface() {
    return Set.of(
        SourcePathsContext.class);
  }

  public enum CheckerAdapterResult {
    SUCCESS,
    FAILURE;
  }
}
